version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: weinvest
      POSTGRES_PASSWORD:
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s webrick -b '0.0.0.0'
    volumes:
      - .:/goal-setting-service
    ports:
      - "4001:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  pgdata:
